# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(225,26,106,0.8) rgba(225,26,106,0.8) 45deg
    col.inactive_border = rgba(98,3,41,1)
    layout = scrolling
    resize_on_border = true
}
