# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = /home/Maggie/Pictures/wallpaper/wallpaperflare.com_wallpaper(4).jpg
wallpaper = /home/Maggie/Pictures/wallpaper/wallpaperflare.com_wallpaper(4).jpg
splash = false
