# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(3,252,211,1) rgba(3,252,211,1) 45deg
    col.inactive_border = rgba(27,117,102,1)
    layout = scroller
    resize_on_border = true
}
